name: compile mpp kernel module

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          make \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          gcc-arm-linux-gnueabi \
          g++-arm-linux-gnueabi \
          pkg-config \
          libdrm-dev
    - name: build
      run: |
        cd build/linux/arm
        bash make-Makefiles.bash
        make -j$(nproc)
    - name: Package artifacts
      run: |
        tar czf mpp-rk3566.tar.gz build/linux/arm
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mpp-rk3566
        path: mpp-rk3566.tar.gz
